name: "Run fasttrack"

description: "Download and run fasttrack tasks"

inputs:
  args:
    description: "Arguments to pass to fasttrack"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download & Run fasttrack
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
        ARCH=$(echo "${{ runner.arch }}" | tr '[:upper:]' '[:lower:]')
        [ "$ARCH" = "x64" ] && ARCH="x86_64"
        [ "$ARCH" = "arm64" ] && ARCH="aarch64"

        EXT=""
        if [[ "$OS" == "windows" ]]; then EXT=".exe"; fi

        BINARY_NAME="fasttrack-$ARCH-$OS$EXT"
        TARGET_PATH="${{ github.action_path }}/$BINARY_NAME"

        VERSION="${{ github.action_ref }}"
        if [[ "$VERSION" == "main" || "$VERSION" == "master" || -z "$VERSION" ]]; then
          echo "Looking for newest available release..."
          # Safer way to get the tag name using JSON/JQ
          VERSION=$(gh release list --repo ${{ github.action_repository }} --limit 1 --json tagName --jq '.[0].tagName')
        fi

        if [ ! -f "$TARGET_PATH" ]; then
          echo "::group::Downloading $BINARY_NAME from Release [$VERSION]"
          gh release download "$VERSION" \
            --repo ${{ github.action_repository }} \
            --pattern "$BINARY_NAME" \
            --output "$TARGET_PATH" \
            --clobber || {
              echo "::error::Could not find asset $BINARY_NAME in release $VERSION"
              exit 1
            }
          
          # Only chmod on non-Windows
          [[ "$OS" != "windows" ]] && chmod +x "$TARGET_PATH"
          echo "::endgroup::"
        fi

        "$TARGET_PATH" ${{ inputs.args }}
