name: "Run fasttrack"

description: "Download and run fasttrack tasks"

inputs:
  args:
    description: "Arguments to pass to fasttrack"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download & Run fasttrack
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
        ARCH=$(echo "${{ runner.arch }}" | tr '[:upper:]' '[:lower:]')
        [ "$ARCH" = "x64" ] && ARCH="x86_64"
        [ "$ARCH" = "arm64" ] && ARCH="aarch64"

        BINARY_NAME="fasttrack-$ARCH-$OS"
        TARGET_PATH="${{ github.action_path }}/$BINARY_NAME"

        # Extract version from the 'uses' string or default to latest
        # This regex gets the version after the '@' symbol
        VERSION=$(echo "${{ github.action_ref }}" | grep -oP 'v[\d.]+(-[\w.]+)?' || echo "latest")

        if [ ! -f "$TARGET_PATH" ]; then
          echo "::group::Downloading $BINARY_NAME from Release $VERSION"
          # We add the VERSION variable here to ensure it hits the right release
          gh release download "$VERSION" \
            --repo ${{ github.repository }} \
            --pattern "$BINARY_NAME" \
            --output "$TARGET_PATH" || {
              echo "::error::Release $VERSION not found. Did you publish it?"
              exit 1
            }
          chmod +x "$TARGET_PATH"
          echo "::endgroup::"
        fi

        "$TARGET_PATH" ${{ inputs.args }}
